# Generated by Django 5.2.6 on 2025-10-01 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0003_category_deleted_at_category_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_deleted',
        ),
    ]
