# Generated by Django 5.2.6 on 2025-10-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0006_subtask_owner_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('closed', 'Закрыта')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('closed', 'Закрыта')], default='new', max_length=20),
        ),
    ]
